import { Deck } from "./types/types";

export const deck: Deck = [
        {
            id: "1_1",
            type: "gogh",
            name: "Sun flower",
            effect: "double",
            url: "/img/cards/gogh/1_1_Sunflower.png",
        },
        {
            id: "1_2",
            type: "gogh",
            name: "Self-Portrait",
            effect: "double",
            url: "/img/cards/gogh/1_2_Self-Portrait.png",
        },
        {
            id: "1_3",
            type: "gogh",
            name: "Terrasse du cafe le foir",
            effect: "double",
            url: "/img/cards/gogh/1_3_Terrasse.png",
        },
        {
            id: "1_4",
            type: "gogh",
            name: "Iris vase",
            effect: "public",
            url: "/img/cards/gogh/1_4_Iris.png",
        },
        {
            id: "1_5",
            type: "gogh",
            name: "Church of auvers",
            effect: "public",
            url: "/img/cards/gogh/1_5_Church.png",
        },
        {
            id: "1_6",
            type: "gogh",
            name: "Old Man Tanguy",
            effect: "public",
            url: "/img/cards/gogh/1_6_Old.png",
        },
        {
            id: "1_7",
            type: "gogh",
            name: "Cypress",
            effect: "oneVoice",
            url: "/img/cards/gogh/1_7_Cypress.png",
        },
        {
            id: "1_8",
            type: "gogh",
            name: "Woman of arles",
            effect: "oneVoice",
            url: "/img/cards/gogh/1_8_Woman.png",
        },
        {
            id: "1_9",
            type: "gogh",
            name: "Sad old man",
            effect: "oneVoice",
            url: "/img/cards/gogh/1_9_Old",
        },
        {
            id: "1_10",
            type: "gogh",
            name: "Gauguin armchair",
            effect: "bid",
            url: "/img/cards/gogh/1_10_Gauguin.png",
        },
        {
            id: "1_11",
            type: "gogh",
            name: "Iris vase",
            effect: "bid",
            url: "/img/cards/gogh/1_11_Red.png",
        },
        {
            id: "1_12",
            type: "gogh",
            name: "Skeleton with a cigarette",
            effect: "bid",
            url: "/img/cards/gogh/1_12_Skeleton.png",
        },
        {
            id: "1_13",
            type: "gogh",
            name: "Sun flower(12 pieces)",
            effect: "limit",
            url: "/img/cards/gogh/1_13_sun12.png",
        },
        {
            id: "1_14",
            type: "gogh",
            name: "Self Portrait(monk)",
            effect: "limit",
            url: "/img/cards/gogh/1_14_monk.png",
        },
        {
            id: "1_15",
            type: "gogh",
            name: "Self Portrait(straw hat)",
            effect: "limit",
            url: "/img/cards/gogh/1_15_straw.png",
        },
        {
            id: "1_16",
            type: "gogh",
            name: "Prison courtyard",
            effect: "public",
            url: "/img/cards/gogh/1_16_prison.png",
        },
    
]